import { useState, useEffect } from 'react';
import {
  Activity, AlertTriangle, Search, Server, ShieldAlert, Zap,
  Terminal, Cpu, BarChart3, Link as LinkIcon, Lock, Eye,
  Database, Wifi, Battery, Clock, Hash, FileText, Download, Share2, CheckCircle,
  Sun, Moon // Iconos para el tema
} from 'lucide-react';
import { jsPDF } from "jspdf";
import './App.css';

const APP_ID = import.meta.env.VITE_ALGOLIA_APP_ID;
const API_KEY = import.meta.env.VITE_ALGOLIA_API_KEY;
const AGENT_URL = import.meta.env.VITE_AGENT_URL;

function App() {
  const [incidentInput, setIncidentInput] = useState('');
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [time, setTime] = useState(new Date().toLocaleTimeString());

  const [artifacts, setArtifacts] = useState({ ips: [], codes: [], paths: [] });
  const [copyStatus, setCopyStatus] = useState('');

  // ESTADO DEL TEMA (Por defecto 'dark')
  const [theme, setTheme] = useState('dark');

  useEffect(() => {
    const timer = setInterval(() => setTime(new Date().toLocaleTimeString()), 1000);
    return () => clearInterval(timer);
  }, []);

  // Efecto para cambiar la clase del body cuando cambia el tema
  useEffect(() => {
    document.body.className = theme;
  }, [theme]);

  const toggleTheme = () => {
    setTheme(prev => prev === 'dark' ? 'light' : 'dark');
  };

  // INTELIGENCIA CLIENT-SIDE
  useEffect(() => {
    if (!incidentInput) {
      setArtifacts({ ips: [], codes: [], paths: [] });
      return;
    }
    const ipRegex = /\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b/g;
    const ips = incidentInput.match(ipRegex) || [];
    const codeRegex = /\b(5\d{2}|4\d{2}|0x[0-9a-fA-F]+|ERR_[A-Z_]+)\b/g;
    const codes = incidentInput.match(codeRegex) || [];
    const pathRegex = /(\/[\w\-\.]+)+\b/g;
    const paths = incidentInput.match(pathRegex) || [];

    setArtifacts({
      ips: [...new Set(ips)].slice(0, 3),
      codes: [...new Set(codes)].slice(0, 3),
      paths: [...new Set(paths)].slice(0, 2)
    });
  }, [incidentInput]);

  const handleAnalyze = async () => {
    if (!incidentInput.trim()) return;
    setLoading(true); setError(''); setResult(null);

    try {
      const response = await fetch(AGENT_URL, {
        method: 'POST',
        headers: {
          'X-Algolia-Application-Id': APP_ID,
          'X-Algolia-API-Key': API_KEY,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ messages: [{ role: "user", content: incidentInput }] })
      });

      if (!response.ok) throw new Error(`Status Code: ${response.status}`);
      const textResponse = await response.text();

      const lines = textResponse.split('\n');
      let fullJsonString = "";
      for (const line of lines) {
        if (line.startsWith('0:')) {
          try { fullJsonString += JSON.parse(line.substring(2)); } catch (e) { /* ignore */ }
        }
      }
      if (!fullJsonString) throw new Error("DATA STREAM CORRUPTED.");

      const cleanJson = fullJsonString.replace(/```json/g, '').replace(/```/g, '').trim();
      setResult(JSON.parse(cleanJson));

    } catch (err) {
      console.error(err);
      setError(`CRITICAL FAILURE: ${err.message}`);
    } finally {
      setLoading(false);
    }
  };

  const generatePDF = () => {
    if (!result) return;
    const doc = new jsPDF();
    const date = new Date().toLocaleString();
    const id = Math.floor(Math.random() * 99999);

    doc.setFont("courier", "bold");
    doc.setFontSize(20);
    doc.text("INCIDENT TRIAGE REPORT", 20, 20);
    doc.setFontSize(10);
    doc.text(`ID: INC-${id}`, 20, 30);
    doc.text(`DATE: ${date}`, 20, 35);
    doc.text("GENERATED BY: SILENT TRIAGE AI", 20, 40);
    doc.line(20, 45, 190, 45);

    doc.setFontSize(12);
    doc.text(`SEVERITY: ${result.severity}`, 20, 55);
    doc.text(`CONFIDENCE SCORE: ${result.confidence_score}%`, 20, 60);

    doc.setFontSize(14);
    doc.text("PROBABLE CAUSE:", 20, 75);
    doc.setFont("courier", "normal");
    doc.setFontSize(11);
    const causeLines = doc.splitTextToSize(result.probable_cause, 170);
    doc.text(causeLines, 20, 82);

    doc.setFont("courier", "bold");
    doc.setFontSize(14);
    doc.text("RECOMMENDED ACTION:", 20, 110);
    doc.setFont("courier", "normal");
    doc.setFontSize(11);
    const actionLines = doc.splitTextToSize(result.recommended_action, 170);
    doc.text(actionLines, 20, 117);

    doc.line(20, 140, 190, 140);
    doc.setFontSize(10);
    doc.text("TECHNICAL ARTIFACTS DETECTED:", 20, 150);
    if (artifacts.ips.length) doc.text(`IPs: ${artifacts.ips.join(", ")}`, 20, 156);
    if (artifacts.codes.length) doc.text(`Error Codes: ${artifacts.codes.join(", ")}`, 20, 162);

    if (result.related_incident_ids) {
      doc.text(`Reference Incident: ${result.related_incident_ids}`, 20, 175);
    }
    doc.save(`INCIDENT_REPORT_${id}.pdf`);
  };

  const copyJiraFormat = () => {
    if (!result) return;
    const jiraText = `h1. Incident Report: ${result.severity}\n*Date:* ${new Date().toLocaleString()}\n*AI Confidence:* ${result.confidence_score}%\n\nh2. Diagnosis\n*Probable Cause:* ${result.probable_cause}\n*Reference:* ${result.related_incident_ids || 'N/A'}\n\nh2. Remediation\n{panel:title=Recommended Action|borderStyle=solid|borderColor=#ff0000}\n${result.recommended_action}\n{panel}\n\nh3. Technical Context\n* Detected IPs: ${artifacts.ips.join(', ') || 'None'}\n* Error Codes: ${artifacts.codes.join(', ') || 'None'}`;
    navigator.clipboard.writeText(jiraText);
    setCopyStatus('jira');
    setTimeout(() => setCopyStatus(''), 2000);
  };

  const getSeverityConfig = (sev) => {
    const s = sev ? sev.toUpperCase() : '';
    if (s.includes('P0')) return { color: '#ff003c' };
    if (s.includes('P1')) return { color: '#ff9a00' };
    if (s.includes('P2')) return { color: '#fcee0a' };
    if (s.includes('P3')) return { color: '#00f0ff' };
    return { color: '#7e8c9f' };
  };

  const sevConfig = result ? getSeverityConfig(result.severity) : {};

  return (
    <div className="app-container">
      <div className="scanline"></div>
      <div className="hud-corner top-left"></div>
      <div className="hud-corner top-right"></div>
      <div className="hud-corner bottom-left"></div>
      <div className="hud-corner bottom-right"></div>

      <div className="hud-meta top">
        <span><Lock size={12} /> ENCRYPTED STREAM</span>
        <span>LATENCY: 12ms</span>
      </div>

      <aside className="sidebar">
        <div className="brand-mark"><ShieldAlert size={32} color="var(--neon-cyan)" /></div>
        <div className="nav-items">
          <div className="nav-item active"><Activity /></div>
          <div className="nav-item"><Database /></div>
        </div>
        <div className="sys-status">
          <div className="status-row"><Wifi size={14} /> ONLINE</div>

          {/* BOTÓN DE TEMA EN EL SIDEBAR */}
          <div className="status-row theme-toggle" onClick={toggleTheme} style={{ cursor: 'pointer', marginTop: 10 }}>
            {theme === 'dark' ? <Sun size={14} /> : <Moon size={14} />}
            {theme === 'dark' ? ' LIGHT' : ' DARK'}
          </div>
        </div>
      </aside>

      <div className="content-wrapper">
        <header className="header">
          <div className="header-content">
            <div className="title-group">
              <h1 className="glitch-text" data-text="SILENT TRIAGE">SILENT TRIAGE</h1>
              <span className="version-tag">PROTOCOL V.2.0.4</span>
            </div>
            <div className="live-clock">
              <Clock size={16} /> {time} <span className="blinking-dot">●</span> LIVE
            </div>
          </div>
          <div className="header-decoration-line"></div>
        </header>

        <main className="main-grid">
          <section className="input-panel glass-frame">
            <div className="frame-header">
              <span className="frame-title"><Terminal size={14} /> TERMINAL_INPUT // </span>
              <div className="artifacts-mini">
                {artifacts.ips.length > 0 && <span className="art-badge ip">IP DETECTED</span>}
                {artifacts.codes.length > 0 && <span className="art-badge err">ERR CODE</span>}
              </div>
            </div>

            <div className="terminal-body">
              <div className="line-numbers">
                <span>01</span><span>02</span><span>03</span><span>04</span>
              </div>
              <textarea
                value={incidentInput}
                onChange={(e) => setIncidentInput(e.target.value)}
                placeholder="> INJECT LOG STREAM HERE..."
                spellCheck="false"
              />
            </div>

            <div className="action-area">
              <button
                onClick={handleAnalyze}
                disabled={loading || !incidentInput}
                className={`cyber-btn ${loading ? 'scanning' : ''}`}
              >
                <span className="btn-content">
                  {loading ? 'RUNNING DIAGNOSTICS...' : 'EXECUTE ANALYSIS'}
                </span>
              </button>
            </div>
            {error && <div className="error-readout"><AlertTriangle size={16} /> {error}</div>}
          </section>

          <section className="result-panel">
            {!result && !loading && (
              <div className="empty-state">
                <div className="hologram-circle"><Search size={40} /></div>
                <p>AWAITING DATA STREAM</p>
              </div>
            )}

            {loading && (
              <div className="loading-state">
                <div className="cyber-loader"></div>
                <div className="decoding-text">
                  <span>PARSING TELEMETRY...</span>
                  <span>SEARCHING KNOWLEDGE BASE...</span>
                </div>
              </div>
            )}

            {result && (
              <div className="triage-card" style={{ '--sev-color': sevConfig.color }}>
                <div className="card-top-bar">
                  <span className="card-id">INC-ID: {Math.floor(Math.random() * 99999)}</span>
                  <div className="severity-flag" style={{ background: sevConfig.color }}>
                    {result.severity}
                  </div>
                </div>

                <div className="card-content">
                  {(artifacts.ips.length > 0 || artifacts.codes.length > 0) && (
                    <div className="artifacts-panel">
                      <div className="art-header"><Hash size={12} /> TELEMETRY EXTRACTED</div>
                      <div className="art-grid">
                        {artifacts.ips.map(ip => <span key={ip} className="art-tag ip">{ip}</span>)}
                        {artifacts.codes.map(code => <span key={code} className="art-tag err">{code}</span>)}
                        {artifacts.paths.map(path => <span key={path} className="art-tag path">{path}</span>)}
                      </div>
                    </div>
                  )}

                  <div className="data-row">
                    <div className="data-label">RECOMMENDED ACTION</div>
                    <div className="data-value highlight typewriter">
                      <Zap size={20} color={sevConfig.color} />
                      {result.recommended_action}
                    </div>
                  </div>

                  <div className="grid-split">
                    <div className="data-box">
                      <div className="box-header"><Eye size={14} /> PROBABLE CAUSE</div>
                      <p>{result.probable_cause}</p>
                    </div>

                    <div className="data-box stats-box">
                      <div className="box-header"><BarChart3 size={14} /> CONFIDENCE</div>
                      <div className="big-number" style={{ color: sevConfig.color }}>
                        {result.confidence_score}%
                      </div>
                      <div className="confidence-bar">
                        <div className="bar-fill" style={{ width: `${result.confidence_score}%`, background: sevConfig.color }}></div>
                      </div>
                    </div>
                  </div>

                  {/* AQUÍ ESTABA EL ERROR: AHORA ESTÁ DENTRO DEL CONTENEDOR */}
                  {result.related_incident_ids && result.related_incident_ids.length > 0 && (
                    <div className="footer-ref">
                      <div className="ref-label">
                        <LinkIcon size={12} /> MATCHED INCIDENT:
                      </div>
                      <div className="ref-values">
                        {Array.isArray(result.related_incident_ids)
                          ? result.related_incident_ids.map((id, index) => (
                            <span key={index} className="ref-tag">
                              {id} <Share2 size={10} style={{ marginLeft: 4, opacity: 0.5 }} />
                            </span>
                          ))
                          : <span className="ref-tag">{result.related_incident_ids}</span>
                        }
                      </div>
                    </div>
                  )}

                  <div className="export-grid">
                    <button className="export-btn pdf" onClick={generatePDF}>
                      <Download size={16} /> DOWNLOAD PDF REPORT
                    </button>
                    <button className="export-btn jira" onClick={copyJiraFormat}>
                      {copyStatus === 'jira' ? <CheckCircle size={16} /> : <Share2 size={16} />}
                      {copyStatus === 'jira' ? 'JIRA FORMAT COPIED' : 'COPY FOR JIRA'}
                    </button>
                  </div>
                </div>
              </div>
            )}
          </section>
        </main>
      </div>
    </div>
  );
}

export default App;